name: welcomesharks

services:
  - name: frontend
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
    source_dir: .
    routes:
      - path: /

  - name: worker
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
    source_dir: worker
    routes: []  # ✅ this line is now valid
