name: welcomesharks

services:
  - name: frontend
    environment_slug: html
    source_dir: /
    output_dir: /
    routes:
      - path: /

functions:
  - name: submit
    source_dir: functions/submit
